const products = [
  { id: 1, name: 'Hoodie', price: 25, gender: 'male', nationality: 'USA' },
  { id: 2, name: 'Shirt', price: 20, gender: 'male', nationality: 'USA'},
  { id: 3, name: 'Mens_Suit', price: 30, gender: 'male', nationality: 'USA'},
  { id: 4, name: 'Vintage', price: 18, gender: 'male', nationality: 'USA' },
  { id: 5, name: 'Mens-Suit', price: 35, gender: 'male', nationality: 'USA'},
  { id: 6, name: 'Jeans', price: 22, gender: 'female', nationality: 'USA' },
  { id: 7, name: 'Top', price: 28, gender: 'female', nationality: 'USA'},
  { id: 8, name: 'Classic_Gown', price: 19, gender: 'female', nationality: 'USA' },
  { id: 9, name: 'Pagamas', price: 32, gender: 'female', nationality: 'USA' },
  { id: 10, name: 'Gown', price: 24, gender: 'female', nationality: 'USA'},
  { id: 11, name: 'Gown', price: 15, gender: 'female', nationality: 'India'},
  { id: 12, name: 'Pagamas', price: 26, gender: 'female', nationality: 'India' },
  { id: 13, name: 'Gown', price: 38, gender: 'female', nationality: 'India'},
  { id: 14, name: 'Lengha', price: 21, gender: 'female', nationality: 'India' },
  { id: 15, name: 'Classic_Gown', price: 40, gender: 'female', nationality: 'India'},
  { id: 16, name: 'Men_Suit', price: 29, gender: 'male', nationality: 'India' },
  { id: 17, name: 'T_Shirt', price: 18, gender: 'male', nationality: 'India'},
  { id: 18, name: 'Jacket', price: 33, gender: 'male', nationality: 'India' },
  { id: 19, name: 'Polo', price: 28, gender: 'male', nationality: 'India'},
  { id: 20, name: 'Vintage', price: 45, gender: 'male', nationality: 'India' },
  { id: 21, name: 'Jeans_Jacket', price: 24, gender: 'male', nationality: 'Nigeria'},
  { id: 22, name: 'Isiagu', price: 27, gender: 'male', nationality: 'Nigeria' },
  { id: 23, name: 'white_Shirt', price: 30, gender: 'male', nationality: 'Nigeria'},
  { id: 24, name: 'Polo', price: 22, gender: 'male', nationality: 'Nigeria' },
  { id: 25, name: 'tee', price: 16, gender: 'male', nationality: 'Nigeria'},
  { id: 26, name: 'African_clothes', price: 42, gender: 'female', nationality: 'Nigeria' },
  { id: 28, name: 'Top', price: 25, gender: 'female', nationality: 'Nigeria'},
  { id: 29, name: 'Pagamas', price: 35, gender: 'female', nationality: 'Nigeria'},
  { id: 30, name: 'Black_Polo', price: 28, gender: 'female', nationality: 'Nigeria' },
  { id: 31, name: 'Top', price: 10, gender: 'female', nationality: 'UK'},
  { id: 32, name: 'Pagamas', price: 15, gender: 'female', nationality: 'UK' },
  { id: 33, name: 'Jeans', price: 25, gender: 'female', nationality: 'UK'},
  { id: 34, name: 'Sweater', price: 30, gender: 'female', nationality: 'UK' },
  { id: 35, name: 'Suit', price: 40, gender: 'female', nationality: 'UK'},
  { id: 36, name: 'Shirt', price: 18, gender: 'male', nationality: 'UK' },
  { id: 37, name: 'Jeans_Jacket', price: 50, gender: 'male', nationality: 'UK'},
  { id: 38, name: 'T_Shirt', price: 22, gender: 'male', nationality: 'UK' },
  { id: 39, name: 'Mens_Suit', price: 60, gender: 'male', nationality: 'UK'},
  { id: 40, name: 'Hoodie', price: 28, gender: 'male', nationality: 'UK' },
  { id: 41, name: 'Polo', price: 45, gender: 'male', nationality: 'China'},
  { id: 42, name: 'Sweater', price: 32, gender: 'male', nationality: 'China' },
  { id: 43, name: 'T_Shirt', price: 20, gender: 'male', nationality: 'China'},
  { id: 44, name: 'Vintage', price: 38, gender: 'male', nationality: 'China' },
  { id: 45, name: 'Jacket', price: 35, gender: 'male', nationality: 'China'},
  { id: 46, name: 'Classic_Top', price: 26, gender: 'female', nationality: 'China' },
  { id: 47, name: 'Classic_Blouse', price: 55, gender: 'female', nationality: 'China'},
  { id: 48, name: 'Gown', price: 30, gender: 'female', nationality: 'China' },
  { id: 49, name: 'Pagamas', price: 15, gender: 'female', nationality: 'China'},
  { id: 50, name: 'Top', price: 22, gender: 'female', nationality: 'China' },

];

export default products;
